### PR TITLE
ci: Install macOS Vulkan dependencies from official SDK release.

### PR DESCRIPTION
**Pull request by Steveice10**
Addressing concerns around Homebrew builds of MoltenVK being targeted for the CI host's macOS version rather than the earliest supported version (currently 10.13). Instead of installing from Homebrew we can install the Vulkan SDK from the official release, which contains universal builds for the earliest supported OS version.

I had to add wget to the list of tools to install as well to work around an issue where Homebrew might update a dependency of wget as part of another update but not wget itself, for some reason.

Resulting builds: https://github.com/Steveice10/citra/actions/runs/3841767403

Tested removing my Vulkan SDK install and running the output app, and everything worked as expected.

### CODE REVIEW

**Review by GPUCode — APPROVED** [review]
Many thanks for the recent MacOS changes

**Comment by UltraHDR** [comment]
Thanks for your hard work!
Have you seen this error? The previous builds also didn't work for me

I'm on an Apple Silicon Mac and only have the dependencies installed using ARM brew
```
/Users/ultrahdr/Downloads/macos/head/citra-qt.app/Contents/MacOS/citra-qt 
libc++abi: terminating with uncaught exception of type vk::IncompatibleDriverError: vk::createInstance: ErrorIncompatibleDriver
zsh: abort      /Users/ultrahdr/Downloads/macos/head/citra-qt.app/Contents/MacOS/citra-qt
```
Thanks

**Comment by Steveice10** [comment]
I believe I had that error early on before the portability subset stuff was enabled in the code to allow loading MoltenVK… Assuming you’re using the latest Vulkan code I’m not sure why you would get that

**Comment by UltraHDR** [comment]
@Steveice10 Thanks for your response. I couldn't get it working using the GPUCode branch

 but the build from https://github.com/Steveice10/citra/actions/runs/3861375075 worked!!

**Pull request merged**
