### PR TITLE
rasterizer_cache: Handle texture swizzle case with unaligned offsets in same tile.

### PR DESCRIPTION
**Pull request by Steveice10**
If the offsets for a texture download are both unaligned and in the same tile, when the start offset is aligned up and the end offset is aligned down the end offset will end up less than the start offset. Since there are already separate cases to handle copying unaligned parts, we can simply skip the middle part of the copy when there are no fully aligned tiles to copy within the address range, by checking for this condition.

Fixes a crash in Mario Kart 7 when the title screen enters the auto demo.

### CODE REVIEW

**Comment by GPUCode** [comment]
Can you test if current Nightly/Canary also has this bug? I don't remember experiencing this crash when entering the demo

**Comment by Steveice10** [comment]
Current upstream calculates using pointer math instead of using offsets, which has an (unintended?) side effect of avoiding this issue.

Upstream: https://github.com/citra-emu/citra/blob/master/src/video_core/rasterizer_cache/morton_swizzle.h#L106

Vulkan: https://github.com/GPUCode/citra/blob/vulkan-2/src/video_core/rasterizer_cache/texture_codec.h#L311

With pointer math, the resulting pointer will be less than the start pointer without underflowing, which ends up skipping the copies in that section. The Vulkan branch version uses a zero-based offset instead, which underflows causing middle copy logic to execute and go out-of-bounds.

**Comment by GPUCode** [comment]
Hm yeah after switching to offsets unearthed a bunch of overflows/underflows in the previous implementation (I remember LinearNextTile would underflow because the code didn't check the y coordinate). I'll merge in this case, thanks! Also on this topic I noticed that your recent PR causes FE Echoes to crash (it didn't crash on 25fe723fa69306f74555c70f30444d16a6dbbc8f so it must be the commits after).

**Comment by Steveice10** [comment]
> Also on this topic I noticed that your recent PR causes FE Echoes to crash (it didn't crash on https://github.com/GPUCode/citra/commit/25fe723fa69306f74555c70f30444d16a6dbbc8f so it must be the commits after).

I remember there was a crash that was fixed by https://github.com/GPUCode/citra/commit/8fcc3d2121cb6eeffaed9274f4f9c26375306501, there's still another crash even after that? Do you know where in the game it crashes so I can reproduce?

**Comment by GPUCode** [comment]
Seems the problem was that my async-shaders branch wasn't up-to-date so didn't have that commit.

**Pull request merged**
